site:
    title: "tensor's dev blog"
    subtitle: "构建只为纯粹书写的博客"
    limit: 10
    theme: theme
    lang: zh
    url: "http://www.chole.io/blog"
    comment: username
    logo: "-/images/pfp2.jpg"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "tensor"
        intro: "构建只为纯粹书写的博客"
        avatar: "-/images/pfp2.png"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
